// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsJYfN6WTNRTsCCAAmt631gg7nQL1Zz98',
    appId: '1:976182138807:web:352438eb39d28954d7fa32',
    messagingSenderId: '976182138807',
    projectId: 'final-project-2f65c',
    authDomain: 'final-project-2f65c.firebaseapp.com',
    storageBucket: 'final-project-2f65c.firebasestorage.app',
    measurementId: 'G-LG64B5M4C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF3n9EU07TXsil3yvJfwGLQ9sEjUuKQT0',
    appId: '1:976182138807:android:48e388f0243b0e93d7fa32',
    messagingSenderId: '976182138807',
    projectId: 'final-project-2f65c',
    storageBucket: 'final-project-2f65c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHqHVgwUuSTYekWH_NNZHyaF-W-RB414',
    appId: '1:976182138807:ios:b9b502a3e4db3841d7fa32',
    messagingSenderId: '976182138807',
    projectId: 'final-project-2f65c',
    storageBucket: 'final-project-2f65c.firebasestorage.app',
    androidClientId: '976182138807-bsa4herqt3b1hmbld6ullqjrecnpdfsq.apps.googleusercontent.com',
    iosClientId: '976182138807-ut75s2v6vh6par3j7qfu1h8cq25hh1ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.fontendPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzHqHVgwUuSTYekWH_NNZHyaF-W-RB414',
    appId: '1:976182138807:ios:b9b502a3e4db3841d7fa32',
    messagingSenderId: '976182138807',
    projectId: 'final-project-2f65c',
    storageBucket: 'final-project-2f65c.firebasestorage.app',
    androidClientId: '976182138807-bsa4herqt3b1hmbld6ullqjrecnpdfsq.apps.googleusercontent.com',
    iosClientId: '976182138807-ut75s2v6vh6par3j7qfu1h8cq25hh1ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.fontendPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsJYfN6WTNRTsCCAAmt631gg7nQL1Zz98',
    appId: '1:976182138807:web:cff47b35bcabba55d7fa32',
    messagingSenderId: '976182138807',
    projectId: 'final-project-2f65c',
    authDomain: 'final-project-2f65c.firebaseapp.com',
    storageBucket: 'final-project-2f65c.firebasestorage.app',
    measurementId: 'G-LRHZVNTSCY',
  );
}
